import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { Card } from "@/components/ui/card";
import { PageHeader } from "@/components/shared/page-header";

export const dynamic = "force-dynamic";

export default async function EmployeesPage() {
  let employees: { id: string; firstName: string; lastName: string; email: string; employeeCode: string; status: string; department: { name: string } | null; designation: { title: string } | null }[] = [];
  try { employees = await prisma.employee.findMany({ orderBy: { createdAt: "desc" }, include: { department: true, designation: true } }); } catch { /* Show the empty state during first-run setup. */ }
  return <><PageHeader title="Employees" description="Manage people, roles, and employment information in one place." action={{ label: "Add employee", href: "/employees/new" }} /><Card><div className="mb-5 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="font-semibold text-slate-900">Employee directory</h2><p className="text-sm text-slate-500">{employees.length} records in this workspace</p></div><input aria-label="Search employees" className="rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-cyan-500" placeholder="Search employees" /></div>{employees.length ? <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-slate-100 text-xs uppercase tracking-wider text-slate-400"><tr><th className="pb-3 font-semibold">Employee</th><th className="pb-3 font-semibold">Department</th><th className="pb-3 font-semibold">Role</th><th className="pb-3 font-semibold">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{employees.map((employee) => <tr key={employee.id} className="group"><td className="py-4"><Link href={`/employees/${employee.id}`} className="font-semibold text-slate-900 group-hover:text-cyan-700">{employee.firstName} {employee.lastName}</Link><p className="text-xs text-slate-500">{employee.employeeCode} · {employee.email}</p></td><td className="py-4 text-slate-600">{employee.department?.name ?? "Unassigned"}</td><td className="py-4 text-slate-600">{employee.designation?.title ?? "Unassigned"}</td><td className="py-4"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">{employee.status}</span></td></tr>)}</tbody></table></div> : <div className="border-t border-slate-100 py-14 text-center"><p className="font-medium text-slate-900">No employees yet</p><p className="mt-1 text-sm text-slate-500">Add your first employee to start building the directory.</p></div>}</Card></>;
}
